# Options for analysis running.
linters:
  # See the dedicated "linters" documentation section.
  enable-all: true
  disable:
    - interfacer
    - scopelint
    - deadcode
    - ifshort
    - maligned
    - structcheck
    - exhaustivestruct
    - golint
    - nosnakecase
    - varcheck